on: push
name: ğŸš€ Test project
jobs:
  test:
    name: ğŸ§ª Test project
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v3

      - name: âš™ï¸ Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: â¬‡ï¸ Install dependencies
        run: npm install

      - name: ğŸ§ª Test project
        run: npm run test
